version: '3.8'

services:
  catalog.api:
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - playgrounddb
    ports:
      - "8091:80"

  orders.api:
    build:
      context: .
      dockerfile: Orders.Api/Dockerfile
    container_name: orders.api
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=mssqldb; Initial Catalog=orders; Persist Security Info=True;User ID=sa;Password=Qwerty123456!@#
      - CatalogApi__Url=http://catalog.api/api
    depends_on:
      - mssqldb
    ports:
      - "8093:80"

  playgrounddb:
    image: mongo
    container_name: playgrounddb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db 

  mssqldb:
    container_name: mssqldb
    ports:
      - "1433:1433"
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
        SA_PASSWORD: "Qwerty123456!@#"
        ACCEPT_EULA: "Y"

  integration-tests:
    container_name: integration-tests
    image: mcr.microsoft.com/dotnet/sdk:5.0
    environment:
      - OrdersApiUrl=http://orders.api/api
    volumes:
      - .:/src
      - ../test:/test
    working_dir: /src
    command:
      [
        "dotnet",
        "test",
        "Tests/Orders.Tests/Orders.Tests.csproj"
      ]
    depends_on:
      - orders.api
      - mssqldb

volumes:
  mongo_data: