version: '3.8'

services:
  playgrounddb:
    image: mongo
    container_name: playgrounddb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db 

  catalog.api:
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - playgrounddb
    ports:
      - "8091:80"

  users.api:
    build:
      context: .
      dockerfile: Users.Api/Dockerfile
    container_name: users.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
    ports:
      - "8092:80"

  users.worker:
    build:
      context: .
      dockerfile: Users.Worker/Dockerfile
    restart: always
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "5672:5672"
    - "15672:15672"

volumes:
  mongo_data: